Реализует задачу «Модуляция (часть 1)»
htmlacademy-javascript/816829-kekstagram-21 pull request #4
Opened 2020-10-21 22:36 UTC by ampu

Допустимо ли решение с pictureClickCallback? Есть ли более грамотные варианты?

2020-10-22 20:15 UTC, AlexMasterov requested changes

2020-10-22 20:16 UTC, AlexMasterov commented
> Допустимо ли решение с pictureClickCallback?

Допустимо и считает хорошим для JS1 😃

2020-10-23 18:25 UTC, ampu commented
EventType и ClassName заинлайнил. Их идея была в том, чтобы по верхним строкам модуля примерно понимать, что будет происходить дальше. Общее перечисление такой возможности меня лишает.
Да и не хочется увеличивать scope этих перечислений.

Подойдет ли такой вариант? 
Или нужно будет делать одно общее перечисление и выносить в отдельный модуль?

2020-10-25 04:34 UTC, AlexMasterov commented
<details>
<summary>Покажи ответ</summary>

> Их идея была в том, чтобы по верхним строкам модуля примерно понимать, что будет происходить дальше

Советую попробовать уменьшить scope самих модулей, чтобы для понимания их содержания не требовалось подобного 😃 Начать можно с доработке `getHashtagsError`.

<details>
<summary>form.js | getHashtagsError</summary>

https://github.com/htmlacademy-javascript/816829-kekstagram-21/blob/234f1e57ca8ac2bb7ee982b2899b0a87dd0919e3/js/form.js#L149-L154
</details>

Можно перенести этот блок с кодом парсинга поля DOM-элемента на уровень выше, например, в `reportHashtagsValidity`, а в саму функцию передавать готовый массив. Это позволит окончательно разделить (бизнес) логику от (побочного) эффекта, что сделает функцию чистой и независимой от окружения браузера. Такую функцию будет просто вынести в отдельный модуль и тестировать вне браузера (или в его консоли).

Подобное разделение и локализация эффектов на верхних уровнях приложения — довольно общий принцип, которые применяется осознанно во многих языках.

<details>
<summary>form.js | getHashtagsError</summary>

https://github.com/htmlacademy-javascript/816829-kekstagram-21/blob/234f1e57ca8ac2bb7ee982b2899b0a87dd0919e3/js/form.js#L158
https://github.com/htmlacademy-javascript/816829-kekstagram-21/blob/234f1e57ca8ac2bb7ee982b2899b0a87dd0919e3/js/form.js#L161
</details>

Желательно также попробовать реализовать проверку дубликатов в общем цикле, чтобы убрать цикл с `.some` и сократить общие количество циклов в решение для валидации (см. [`Б 24`](https://up.htmlacademy.ru/javascript/21/criteries#b24)).

> Подойдет ли такой вариант?

С `EventType` и `ClassName` вполне.

> Или нужно будет делать одно общее перечисление и выносить в отдельный модуль?

Если получится вынести функцию валидации тегов в отдельный модуль, то далее можно попробовать сделать обработку и форматирования ошибок более гибкой. Сейчас функция валидация возвращает статичный текст на русском языке, а его отсутствие (пустая строка) обрабатывается как отсутствие ошибки. Вместо этого будет достаточно возвращать только тип ошибки (используя простое перечисление), а само сообщение формировать в другом месте (используя на основе перечисления словарь из слов или функций). Это позволит свободно изменять язык и формат сообщения.

> Если возвращать результат валидации в виде объекта: `{ errorType, tag, hasError }`, то можно упростить проверку на наличие ошибки (= инкапсуляция) и использовать невалидный тег для создания более информативного сообщения

В этом случае для типов ошибок валидации тегов будет уместно использовать общие перечисление, причем в отдельном модуле.

> Создание строки "фильтра" для свойства `.filter` тоже можно вынести в отдельный модуль
</details>

2020-10-25 04:34 UTC, AlexMasterov commented
👍🏻

2020-10-25 04:34 UTC, merged